version: 2
jobs:
  build1:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    parallelism: 4
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - ~
          key: app-{{ checksum ".circleci/config.yml" }}

#      - run:
#          name: Run Findbugs
#          command: ./gradlew findbugs



  build2:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - restore_cache:
          key: app-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Checkstyle Tests
          command: ./gradlew checkstyle
      - save_cache:
          paths:
            - ~
          key: app-{{ checksum ".circleci/config.yml" }}1

  build3:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - restore_cache:
          key: app-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run PMD Tests
          command: ./gradlew pmd
      - save_cache:
          paths:
            - ~
          key: app-{{ checksum ".circleci/config.yml" }}2

  build4:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - restore_cache:
          key: app-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run Lint Tests
          command: ./gradlew lint test
      - save_cache:
          paths:
            - ~
          key: app-{{ checksum ".circleci/config.yml" }}3

  build5:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}1
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}2
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}3
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - restore_cache:
          key: app-{{ checksum ".circleci/config.yml" }}
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      - run:
          name: Build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks
      - deploy:
          name: Deploy APK.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash ./scripts/deploy-fabric.sh
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build1
      - build2:
          requires:
            - build1
      - build3:
          requires:
            - build1
      - build4:
          requires:
            - build1
      - build5:
          requires:
            - build1
            - build2
            - build3
            - build4
